name: React CI

on:
  pull_request:
    paths-ignore:
      - 'react-ts/**.ts'
      - 'react-ts/**.tsx'
      - 'react-ts/**.json'
      - 'react-ts/**.js'
      - 'react-ts/**.jsx'

jobs:
  build:
    name: React CI
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Java CI build not required"'