name: publish

on:
  push:
    branches: [ main ]

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the hello-docker Docker image
      run: |
        docker build . --tag ghcr.io/robmcarrier/budget-app:latest
        docker run ghcr.io/robmcarrier/budget-app:latest
        docker push ghcr.io/robmcarrier/budget-app:latest