name: Java CI

on:
  pull_request:
    paths-ignore:
      - '**.java'
      - 'pom.xml'

jobs:
  build:
    name: Java CI
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Java CI build not required"'